### ISSUE TITLE
Learn R_reg in each level of the tree

### ISSUE THREAD

**Issue by ziqixu-research** [felixwzh/TSGB#1]
Hi! It is a very innovative and helpful model. I am running the public dataset with Amazon, and trying to plot the R_neg node graph as in the paper. I am lost in where I can calculate the R_neg for the tasks and how I can determine if it is a task-wise split or feature-wise split. Could you please give some suggestions? 

Thanks!

**Comment by felixwzh** [comment]
thanks for your interests!
- you can checkout this function for R_neg https://github.com/felixwzh/TSGB/blob/main/src/tree/updater_colmaker.cc#L1319
- and this function is used to determine a task/feature-wise split https://github.com/felixwzh/TSGB/blob/main/src/tree/updater_colmaker.cc#L1509

you may need to change `updater_colmaker.cc` and rebuild to print some logs

**Comment by ziqixu-research** [comment]
Thank you! It is very helpful.
